[pytest]
pythonpath = .
asyncio_mode = auto
# testpaths = tests


# =============== RUN ===============
# ===== all: pytest -v
# ===== just 1_ex: pytest tests/test_etag_cache.py -v
# ===== 1 class_ex: pytest tests/test_etag_cache.py::TestETagCache -v
